### ISSUE TITLE
"malformed JSON string"

### ISSUE THREAD

**Issue by toddgrotenhuis** [pjf/WebService-HabitRPG#32]
I have gotten this message just a handful of times. I suspect it happens when an egg or potion is dropped. (a case that may not be handled by the results parser?) It happens when "plussing" an item.

```
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "<html>\n<head>\n    ...") at /Library/Perl/5.12/JSON/Any.pm line 571.
```
##

**Comment by hoelzro** [comment]
This is fixed in version 0.30 of the module!
