### ISSUE TITLE
Feature request: make current streak on a task available via an accessor

### ISSUE THREAD

**Issue by hoelzro** [pjf/WebService-HabitRPG#36]
I have a script that warns me at 22:00 if I have uncompleted tasks, and tells me the current streak of each so that I know what's at risk.  I currently use `$task->_raw{streak}`; would it be possible to add a public accessor for the current streak?

**Comment by pjf** [comment]
Woah! Activity! Hi! :)

It sounds like we should absolutely have a public accessor! Do you feel like the sort of person to send in a pull request? (No is totally fine, but the inner project manager in me looks for any excuse to gather contributors and more eyes on the codebase.)

~ Paul

**Comment by hoelzro** [comment]
I sure do!  I've taken the liberty of creating PR #37.

**Comment by hoelzro** [comment]
@pjf Have you had a chance to look at my PR? No rush =)

**Comment by pjf** [comment]
@hoelzro : Oh, you are fantastic! I'm sorry for being so quiet, I have a big pile of work and I haven't used Habit in a while, so I *really* appreciate the nudge.

On that note, would you like maintainership of the module? If you're an active user and wish to make changes then that's going to make sure there's the least roadblocks for the code improving.

I'm happy to mark you as a collaborator on this repo, or use github magic of your choice to transfer the repo to you or an organisation created for the purpose, as well as letting PAUSE/CPAN know (although you'll need to remind me of your PAUSE author ID).

**Comment by hoelzro** [comment]
@pjf Sure, why not?  Feel free to mark me as a collaborator here, and if you wish to add me as a comaintainer on PAUSE, I'm RHOELZ there.

**Comment by pjf** [comment]
@hoelzro : Done! Congratulations on your new module! :D

**Comment by hoelzro** [comment]
Fixed!
