### ISSUE TITLE
Score Habit broken after API changes

### ISSUE THREAD

**Issue by eshapard** [pjf/WebService-HabitRPG#39]
They changed servers or something and the API is picky about how you body parameters. This broke a program I wrote.

Running hrpg from the command line (hrpg + "task name"), It seems to score a task but always says "Looks like an item dropped!", and HP, XP, and GP are always +0.00.

The task, of course, remains incomplete on Habitica.

In the Aspiring Comrades guild/forum Alys wrote the following which might be of help:

> Everyone, changes have happened to the servers that Habitica uses which have resulted in the API's score route now needing a body parameter, which can be an empty string. For example, it's necessary to add -d "" as shown below. Ideally, we'll try to make it so that the new requirement stops being necessary since it's a breaking change, but I don't know at the moment if that will be possible.

**Comment by hoelzro** [comment]
@eshapard Thanks for the report - I have an idea on how to fix this, and I'll take care of it sometime this weekend.

**Comment by hoelzro** [comment]
This is fixed in version 0.30 of the module!

**Comment by eshapard** [comment]
You rock!
